config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/about'

devise_for :users, :controllers => { registrations: 'registrations', sessions: 'users/sessions' }

  resources :orders
  resources :promotions
  resources :products
  resources :product_orders
  resources :product_promotions
  
  patch '/orders/checkout/:id', to: 'orders#checkout', as: 'checkoutorder'

   root 'static_pages#home'

end

app/models/product_order.rb
class ProductOrder < ActiveRecord::Base
    belongs_to :order
    belongs_to :product 
   validates_associated  :product
   validates :product_qty, :product_price, presence: true
  validates :product_qty, numericality: {:greater_than => 0}
   end

app/controllers/product_orders_controller.rb
class ProductOrdersController < ApplicationController
   before_action :authenticate_user!
  before_action :set_product_orders, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @product_orders = ProductOrder.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product_orders = ProductOrder.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product=Product.find(product_orders_params[:product_id])
      @productprice=Product.find(product_orders_params[:product_id]).price
      @paramsvar= product_orders_params
  
  if Promotion.joins(product_promotions: [:product]).where('product_id= ? AND start_date < ? AND end_date > ?',@product,Date.today,Date.today).exists? then
  @discountamount=Promotion.joins(product_promotions: [:product]).where('product_id= ? AND start_date < ? AND end_date > ?',@product,Date.today,Date.today).first.discount_amount
  @productadjustedprice = @product.price-(@discountamount/100*@product.price)
   @paramsvar[:product_price] =  @product.price-(@discountamount/100*@product.price)
  
  else
  @productadjustedprice = nil
  @paramsvar[:product_price] =@productprice
  end
      
     @addproduct =current_user.orders.last.product_orders.create(@paramsvar)

    if @addproduct.save
      
      flash[:success] = "Product Added!"
      redirect_to root_url
    else
       flash[:notice] = "Product was not added :("
       
     redirect_to root_url
    end

  
    end
  

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product_order.update(product_orders_params)
        format.html { redirect_to  edit_order_path(Order.last), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_order }
      else
        format.html { render :edit }
        format.json { render json: @product_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product_order.destroy
    @order=session[:order]
    respond_to do |format|
      format.html { redirect_to edit_order_path(@order), notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_orders
      @product_order = ProductOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_orders_params
      params.require(:product_order).permit(:order_id, :product_id, :product_qty, :product_price)
    end
end

app/views/product_orders/_form.html.erb
<%= form_for(@product_order) do |f| %>
    <% if @product_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @product_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

  <br>
   
  <div class="input-field">
   <h2> Item : <%=Product.find(@product_order.product_id).title %> </h2>
    <%= f.number_field :product_qty, :value=> @product_order.product_qty%>
  </div>
    
  
  <p> Line cost :$<%=@product_order.product_price.to_f*@product_order.product_qty.to_f %> </p>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_orders/edit.html.erb
<h1>Editing Product Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @productorder %> |
<%= link_to 'Back', orders_path %>

app/views/product_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Product Orders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_orders.each do |product_order| %>
      <tr>
      <td> <%= product_order.id %> </td>
      <td> <%= product_order.product_id %> </td>
      <td> <%= product_order.product_qty %> </td>
       <td> <%= product_order.product_price %> </td>
     

        <td><%= link_to 'Show', product_order %></td>
        <td><%= link_to 'Edit', edit_product_order_path(product_order) %></td>
        <td><%= link_to 'Destroy', product_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Order', new_product_order_path %>