config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/about'

devise_for :users, :controllers => { registrations: 'registrations', sessions: 'users/sessions' }

  resources :orders
  resources :promotions
  resources :products
  resources :product_orders
  resources :product_promotions
  
  patch '/orders/checkout/:id', to: 'orders#checkout', as: 'checkoutorder'

   root 'static_pages#home'

end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :user
    has_many :product_orders
    has_many :products, through: :product_orders
    validates_associated :user
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
   before_action :authenticate_user!
  before_action :set_order, only: [:checkout, :show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = current_user.orders.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  
       
 
    @shoppingcart=current_user.orders.last
    session[:order]=@shoppingcart.id
    @invoicetotal=0
      @shoppingcart.product_orders.each do |i|
      @invoicetotal+=i.product_price.to_f*i.product_qty.to_f
      end
    
  end

  def checkout
    checkout_cart=@order
   checkout_cart.status=1
   checkout_cart.save
   @order=Order.new(status: 0, user_id: current_user.id)

   @order.save 
    
    respond_to do |format|
      if  checkout_cart.save
        format.html { redirect_to products_path, notice: 'shopping cart was successfully submitted.' }
        format.json { render :show, status: :created, location:  checkout_cart }
      else
        format.html { render :new }
        format.json { render json:  checkout_cart.errors, status: :unprocessable_entity }
      end
    end
    
  end
  
  
  
  # POST /orders
  # POST /orders.json
  def create
  
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
       params.require(:order).permit(:id, :date, :commit, :customer_id, :customer_order_no)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>
   
     <div class="date-field">
   
    <%= hidden_field :date, :value=> Date.current()%>
  </div>
     <div class="field">
 
    <%= f.hidden_field :user_id, :value=>current_user %>
  </div>
   
   <div class="date-field">
   
    <%= hidden_field :status, :value=> 1%>
  </div>
  <table class="table table-hover table-striped table-responsive">
  <tr>
  <th># </th>
  <th>Product Name </th>
  <th>Product Qty </th>
  <th>Product Cost Each </th>
  <th>Line Total </th>
  <th colspan=2></th>
  </tr>
  <% count=0 %>
  <%  @order.product_orders.each do |f| %>
  <tr>
  <% count=count+1%>
   <th scope="row"><%= count.to_s %></th>
 <td> <%=f.product.name %> </td>
 <td> <%=f.product_qty %></td>
<td>  <%=f.product_price %> </td>
<td> <%=f.product_price.to_f*f.product_qty.to_f %> </td>
<td> <%=link_to 'modify', edit_product_order_path(f.id) %> </td>  
<td> <%=link_to 'remove', product_order_path(f.id), method: :delete %> </td>
</tr>    
  <% end %>
  </table>

  <h2> Total Price ex Shipping ex Tax   :$  <%= @invoicetotal %></h2>
  <div class="field">
    <%= f.text_field :customer_order_no %> <b> Your Order Number </b>  <%= f.submit  "update", class: "btn btn-primary"%>
  </div>

   
 
  
  <div  class="actions">

  <%= f.submit 'checkout', formaction: checkoutorder_path(@order),class: "btn btn-success" %>
  </div>
  
<% end %>

app/views/orders/edit.html.erb
<h1>Items in Current Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @order,class: "btn btn-primary" %> |
<%= link_to 'Back', orders_path,class: "btn btn-primary" %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Past Orders</h1>

<table class="table table-striped table-responsive table-hover">
  <thead>
    <tr>
    <th>#</th>
    <th>Order Id </th>
    <th>Date</th>
    <th>Status</th>
    <th>Your order Id</th>
  
    </tr>
  </thead>

  <tbody>
  <%count=0%>
    <% @orders.each do |order| %>
    <% count=count+1%>
      <tr>
      <th scope="row"><%=count.to_s%></th>
      <td> <%= order.id %> </td>
      <td> <%= order.updated_at %> </td>
      <td> <%= if order.status.to_i ===1 then 'being packed' elsif order.status.to_i === 0 then 'in cart' elsif order.status.to_i === 2  then 'shipped' end%>
      <td> <%= order.customer_order_no %> </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path, class: "btn btn-primary" %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path,class: "btn btn-primary" %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_order_path(@order),class: "btn btn-success" %> |
<%= link_to 'Back', orders_path,class: "btn btn-primary" %>