config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/about'

devise_for :users, :controllers => { registrations: 'registrations', sessions: 'users/sessions' }

  resources :orders
  resources :promotions
  resources :products
  resources :product_orders
  resources :product_promotions
  
  patch '/orders/checkout/:id', to: 'orders#checkout', as: 'checkoutorder'

   root 'static_pages#home'

end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
    has_many :product_promotions
    has_many :products, through: :product_promotions
    validates :name, :start_date, :end_date, :discount_amount, presence: true
     validates :discount_amount, numericality: {:greater_than => 0} 
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_promotion, only: [:show, :edit, :update, :destroy]

  # GET /promotions
  # GET /promotions.json
  def index
    @promotions = Promotion.all
  end

  # GET /promotions/1
  # GET /promotions/1.json
  def show
     @products=@promotion.products
  end

  # GET /promotions/new
  def new
    @promotion = Promotion.new
 @products=@promotion.products
  @product_promotions=ProductPromotion.new
  end
  
  def delete_promotion_product
    @b=ProductPromotion.id.where(promotion_id: @promotion, product_id: p)
  end

  # GET /promotions/1/edit
  def edit
        @products=@promotion.products
         @product_promotions=ProductPromotion.new
         session[:promotion]=@promotion.id
  end

  # POST /promotions
  # POST /promotions.json
  def create
  
      @promotion = Promotion.new(promotion_params)

      respond_to do |format|
      if @promotion.save
        format.html { redirect_to edit_promotion_path(@promotion), notice: 'Promotion was successfully created.' }
        format.json { render :show, status: :created, location: @promotion }
        else
        format.html { render :new }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
        end
      end
  
end #end def
  

  # PATCH/PUT /promotions/1
  # PATCH/PUT /promotions/1.json
  def update
    respond_to do |format|
      if @promotion.update(promotion_params)
        format.html { redirect_to @promotion, notice: 'Promotion was successfully updated.' }
        format.json { render :show, status: :ok, location: @promotion }
      else
        format.html { render :edit }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1
  # DELETE /promotions/1.json
  def destroy
    @promotion.destroy
    respond_to do |format|
      format.html { redirect_to products_path, notice: 'Promotion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promotion
      @promotion = Promotion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promotion_params
      params.require(:promotion).permit(:id,:start_date, :end_date,:discount_amount, :name)
    end
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/promotions/_form.html.erb
<div class="container jumbotron">

<%= form_for(@promotion) do |f| %>
  <% if @promotion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@promotion.errors.count, "error") %> prohibited this promotion from being saved:</h2>

  
    </div>
  <% end %>
   <div class="field">
    <%= f.label :name %><br>
     <p><%= f.text_field :name %>
    </p>
    </div>
  <div class="field">
    <%= f.label :start_date %><br>
   <%= f.text_field :start_date, class: "datepicker col-xs-12" %>
    </div>
    <div class="field">
    <%= f.label :end_date %><br>
   <%= f.text_field :end_date, class: "datepicker col-xs-12" %>
    </div>
    <div class="field">
    <%= f.label :discount_amount %><br>
     <p> % <%= f.number_field :discount_amount, step: :any %>
    </p>
    </div>
   
    

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/promotions/edit.html.erb
<div class="jumbotron">
<h1>Editing Promotion</h1>

<%= render 'form' %>
    <table class='table table-hover'>
     <thead>
    <tr>
      <th scope='col'>#</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Year</th>
      <th scope="col">Remove from Promotion</th>
    </tr>
  </thead>
  <% @count= 0.to_i %>
 <% @products.each do |p| %>
      <% @count=@count+1 %>
     <tr>
     <th scope="row"><%= @count %></th>
     <td> <%= p.title %> </td>
     <td> <%= p.author %> </td>
     <td> <%= p.year %> </td>
     <%@b=ProductPromotion.where(promotion_id: @promotion, product_id: p).ids.first %>
     <td> <%=  form_tag(product_promotion_path(:id => @b), method: :delete ) do  %> <%=submit_tag "Delete", class: "btn btn-warning" %> <%end%></td>
     </tr>
     <%end %>
    
    </table>
<h3> Add Products </h3>
<%= form_for(@product_promotions) do |o| %>
<%= select_tag(:product_id, options_from_collection_for_select(Product.all, :id, :title)) %>
<%= hidden_field_tag(:promotion_id, @promotion.id) %>
  <%= o.submit class:"btn btn-success"  %>
  
<% end %>


<%= link_to 'Show', @promotion, class: "btn btn-primary" %> |
<%= link_to 'Back', promotions_path, class: "btn btn-primary" %>

app/views/promotions/index.html.erb
<h1>All Promotions</h1>

<table>
  <thead>
    <tr>
      <th> Promotion Name</th>
      <th> Start Date </th>
      <th> End Date </th>
      <th> Discount </th>
      <th colspan=3> </th>
    </tr>
    
  </thead>

  <tbody>
    <% @promotions.each do |promotion| %>
      <tr>
        <td><%= promotion.name %>  </td>
        <td><%= promotion.start_date.strftime("%Y-%m-%d") %> </td>
        <td><%= promotion.end_date.strftime("%Y-%m-%d") %> </td>
        <td><%= promotion.discount_amount %>
        <td><%= link_to 'Show', promotion, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_promotion_path(promotion), class: "btn btn-success" %></td>
        <td><%= link_to 'Destroy', promotion, method: :delete, class: "btn btn-warning", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Promotion', new_promotion_path , class: "btn btn-primary"%>

app/views/promotions/new.html.erb
<h1>New Promotion</h1>
 

<%= render 'form' %>

<%= link_to 'Back', promotions_path , class: "btn btn-primary"%>

app/views/promotions/show.html.erb
  <div class="field">
   
     <p>Name: <%= @promotion.name %>
    </p>
    </div>
  <div class="field">
    <p> End Date: <%= @promotion.end_date.strftime("%Y-%m-%d") %>
  
    </div>
    <div class="field">
    <p> Start Date: <%= @promotion.start_date.strftime("%Y-%m-%d") %>
  
    </div
    <div class="field">
   
     <p> % Discount <%=@promotion.discount_amount %>
    </p>
    </div>
 <table class='table table-hover'>
     <thead>
    <tr>
      <th scope='col'>#</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Year</th>
     
    </tr>
  </thead>
  <% @count= 0.to_i %>
 <% @products.each do |p| %>
      <% @count=@count+1 %>
     <tr>
     <th scope="row"><%= @count %></th>
     <td> <%= p.title %> </td>
     <td> <%= p.author %> </td>
     <td> <%= p.year %> </td>
    
     </tr>
     <%end %>
    
    </table>

  



<%= link_to 'Edit', edit_promotion_path(@promotion), class: "btn btn-success" %> |
<%= link_to 'Back', promotions_path, class: "btn btn-primary" %>