config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/about'

devise_for :users, :controllers => { registrations: 'registrations', sessions: 'users/sessions' }

  resources :orders
  resources :promotions
  resources :products
  resources :product_orders
  resources :product_promotions
  
  patch '/orders/checkout/:id', to: 'orders#checkout', as: 'checkoutorder'

   root 'static_pages#home'

end

app/views/layouts/_footer.html.erb
 <footer class="foooter">Copyright Tech Reader 2018 
</footer> 

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-expand-md  navbar-light bg-light">
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse " id="navbarSupportedContent">
    <ul class="navbar-nav">
    
      <li class="nav-item active ">
      
        <%=link_to 'Home',  static_pages_home_path, class: "nav-link" %>
        
      </li>
       <li class="nav-item  ">
      
        <%=link_to 'About Us',  static_pages_about_path, class: "nav-link" %>
        
      </li>
      <% if not user_signed_in? %>
         <li class="nav-item">
         <%= link_to 'Registration', new_user_registration_path, class: "nav-link" %>
         </li>
         <li class="nav-item">
         <%=link_to("Log In", new_user_session_path, class: "nav-link") %>
         </li>

     <% else %>
          <li class="nav-item">
         <%= link_to("Log Out", destroy_user_session_path, method: :delete, class: 'nav-link') %>
          </li>
    
            <li class="nav-item">
             <%= link_to 'My Cart', edit_order_path(current_user.orders.last.id), class: "nav-link" %>
            </li>
            <li class="nav-item">
            
             <%= link_to 'My Orders', orders_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
             <%= link_to 'Promotions Administration', promotions_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
             <%= link_to 'Add new Product', new_product_path, class: "nav-link" %>
            </li>
    <% end %>        
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Tech Reader</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<div class='container contents'>
<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>" role='alert'>
            <%= value %>
      </div>
<% end %>
<%= render 'layouts/header' %>

<%= yield %>
<br>
    <%= render_breadcrumbs  class: "breadcrumb-item", style: "font-weight: bold;"%>
<br>
<br>

 


<%= render 'layouts/footer' %>
 </div>
</body>
</html>